version: '3'
services:
  app:
    build: .
    container_name: app
    depends_on:
      - postgres
      - redis
    environment:
      - PG_DATABASE=image-size
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=db
      - PG_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  postgres:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=image-size
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
